name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: "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"
        ADD_LABEL: "approved"
